CREATE TABLE KEYSTORES (
  id      NUMERIC(3, 0) PRIMARY KEY,
  NAME    VARCHAR(100) NOT NULL,
  content BYTEA        NOT NULL
);
CREATE INDEX KEYSTORES_ID_INDEX ON KEYSTORES (id);
CREATE SEQUENCE KEYSTORES_S START 1 CACHE 1;