INSERT INTO CMS_USERS (ID, USERNAME, PASSWORD_HASH, STATUS)
VALUES (NEXTVAL('CMS_USERS_S'), 'CWSFE_CMS_ADMIN', '$2a$10$DvUv.Tit8LGupsjxgoy02.K27jdAMDh0mTwZm1K3mGU3ylQ3zPJ4W', 'N');
INSERT INTO CMS_USER_ROLES (CMS_USER_ID, ROLE_ID) VALUES (
    (SELECT id
     FROM CMS_USERS
     WHERE username = 'CWSFE_CMS_ADMIN'),
    (SELECT id
     FROM CMS_ROLES
     WHERE ROLE_CODE = 'ROLE_CWSFE_CMS_ADMIN')
);
