ALTER TABLE BLOG_POST_IMAGES
    ADD COLUMN last_modified TIMESTAMP NOT NULL DEFAULT now();
ALTER TABLE CMS_NEWS_IMAGES
    ADD COLUMN last_modified TIMESTAMP NOT NULL DEFAULT now();
UPDATE BLOG_POST_IMAGES
SET last_modified = created;
UPDATE CMS_NEWS_IMAGES
SET last_modified = created;

INSERT INTO CMS_GLOBAL_PARAMS (ID, CODE, DEFAULT_VALUE, VALUE, DESCRIPTION) VALUES (
    nextval('CMS_GLOBAL_PARAMS_S'), 'CWSFE_CMS_BLOG_IMAGES_PATH', '/opt/cwsfe_cms/blogImages',
    '/opt/cwsfe_cms/blogImages', 'Path to images for blog'
);

INSERT INTO CMS_GLOBAL_PARAMS (ID, CODE, DEFAULT_VALUE, VALUE, DESCRIPTION) VALUES (
    nextval('CMS_GLOBAL_PARAMS_S'), 'CWSFE_CMS_NEWS_IMAGES_PATH', '/opt/cwsfe_cms/newsImages',
    '/opt/cwsfe_cms/newsImages', 'Path to images for news'
);

ALTER TABLE BLOG_POST_IMAGES
    DROP COLUMN CONTENT;
ALTER TABLE CMS_NEWS_IMAGES
    DROP COLUMN CONTENT;
