ALTER TABLE blog_keywords ALTER COLUMN status TYPE VARCHAR(7) USING status::VARCHAR(7);
UPDATE blog_keywords SET STATUS = 'NEW' WHERE status = 'N';
UPDATE blog_keywords SET STATUS = 'DELETED' WHERE status = 'D';

ALTER TABLE CMS_AUTHORS ALTER COLUMN status TYPE VARCHAR(7) USING status::VARCHAR(7);
UPDATE CMS_AUTHORS SET STATUS = 'NEW' WHERE status = 'N';
UPDATE CMS_AUTHORS SET STATUS = 'DELETED' WHERE status = 'D';

ALTER TABLE CMS_LANGUAGES ALTER COLUMN status TYPE VARCHAR(7) USING status::VARCHAR(7);
UPDATE CMS_LANGUAGES SET STATUS = 'NEW' WHERE status = 'N';
UPDATE CMS_LANGUAGES SET STATUS = 'DELETED' WHERE status = 'D';

ALTER TABLE CMS_USERS ALTER COLUMN status TYPE VARCHAR(7) USING status::VARCHAR(7);
UPDATE CMS_USERS SET STATUS = 'NEW' WHERE status = 'N';
UPDATE CMS_USERS SET STATUS = 'DELETED' WHERE status = 'D';
UPDATE CMS_USERS SET STATUS = 'LOCKED' WHERE status = 'L';

ALTER TABLE CMS_USERS ALTER COLUMN status TYPE VARCHAR(7) USING status::VARCHAR(7);
UPDATE CMS_USERS SET STATUS = 'NEW' WHERE status = 'N';
UPDATE CMS_USERS SET STATUS = 'DELETED' WHERE status = 'D';

ALTER TABLE BLOG_POSTS ALTER COLUMN status TYPE VARCHAR(9) USING status::VARCHAR(9);
UPDATE BLOG_POSTS SET STATUS = 'NEW' WHERE status = 'N';
UPDATE BLOG_POSTS SET STATUS = 'DELETED' WHERE status = 'D';
UPDATE BLOG_POSTS SET STATUS = 'PUBLISHED' WHERE status = 'P';
UPDATE BLOG_POSTS SET STATUS = 'HIDDEN' WHERE status = 'H';

ALTER TABLE BLOG_POST_I18N_CONTENTS ALTER COLUMN status TYPE VARCHAR(9) USING status::VARCHAR(9);
UPDATE BLOG_POST_I18N_CONTENTS SET STATUS = 'NEW' WHERE status = 'N';
UPDATE BLOG_POST_I18N_CONTENTS SET STATUS = 'DELETED' WHERE status = 'D';
UPDATE BLOG_POST_I18N_CONTENTS SET STATUS = 'PUBLISHED' WHERE status = 'P';
UPDATE BLOG_POST_I18N_CONTENTS SET STATUS = 'HIDDEN' WHERE status = 'H';

ALTER TABLE BLOG_KEYWORDS ALTER COLUMN status TYPE VARCHAR(7) USING status::VARCHAR(7);
UPDATE BLOG_KEYWORDS SET STATUS = 'NEW' WHERE status = 'N';
UPDATE BLOG_KEYWORDS SET STATUS = 'DELETED' WHERE status = 'D';

ALTER TABLE BLOG_POST_IMAGES ALTER COLUMN status TYPE VARCHAR(9) USING status::VARCHAR(9);
UPDATE BLOG_POST_IMAGES SET STATUS = 'NEW' WHERE status = 'N';
UPDATE BLOG_POST_IMAGES SET STATUS = 'DELETED' WHERE status = 'D';
UPDATE BLOG_POST_IMAGES SET STATUS = 'PUBLISHED' WHERE status = 'P';

ALTER TABLE BLOG_POST_CODE ALTER COLUMN status TYPE VARCHAR(7) USING status::VARCHAR(7);
UPDATE BLOG_POST_CODE SET STATUS = 'NEW' WHERE status = 'N';
UPDATE BLOG_POST_CODE SET STATUS = 'DELETED' WHERE status = 'D';

ALTER TABLE CMS_BLOG_POST_COMMENTS ALTER COLUMN status TYPE VARCHAR(9) USING status::VARCHAR(9);
UPDATE CMS_BLOG_POST_COMMENTS SET STATUS = 'NEW' WHERE status = 'N';
UPDATE CMS_BLOG_POST_COMMENTS SET STATUS = 'DELETED' WHERE status = 'D';
UPDATE CMS_BLOG_POST_COMMENTS SET STATUS = 'PUBLISHED' WHERE status = 'P';
UPDATE CMS_BLOG_POST_COMMENTS SET STATUS = 'BLOCKED' WHERE status = 'B';
UPDATE CMS_BLOG_POST_COMMENTS SET STATUS = 'SPAM' WHERE status = 'S';

ALTER TABLE CMS_FOLDERS ALTER COLUMN status TYPE VARCHAR(7) USING status::VARCHAR(7);
UPDATE CMS_FOLDERS SET STATUS = 'NEW' WHERE status = 'N';
UPDATE CMS_FOLDERS SET STATUS = 'DELETED' WHERE status = 'D';

ALTER TABLE CMS_NEWS_TYPES ALTER COLUMN status TYPE VARCHAR(7) USING status::VARCHAR(7);
UPDATE CMS_NEWS_TYPES SET STATUS = 'NEW' WHERE status = 'N';
UPDATE CMS_NEWS_TYPES SET STATUS = 'DELETED' WHERE status = 'D';

ALTER TABLE CMS_NEWS ALTER COLUMN status TYPE VARCHAR(9) USING status::VARCHAR(9);
UPDATE CMS_NEWS SET STATUS = 'NEW' WHERE status = 'N';
UPDATE CMS_NEWS SET STATUS = 'DELETED' WHERE status = 'D';
UPDATE CMS_NEWS SET STATUS = 'PUBLISHED' WHERE status = 'P';
UPDATE CMS_NEWS SET STATUS = 'HIDDEN' WHERE status = 'H';

ALTER TABLE CMS_NEWS_I18N_CONTENTS ALTER COLUMN status TYPE VARCHAR(9) USING status::VARCHAR(9);
UPDATE CMS_NEWS_I18N_CONTENTS SET STATUS = 'NEW' WHERE status = 'N';
UPDATE CMS_NEWS_I18N_CONTENTS SET STATUS = 'DELETED' WHERE status = 'D';
UPDATE CMS_NEWS_I18N_CONTENTS SET STATUS = 'PUBLISHED' WHERE status = 'P';
UPDATE CMS_NEWS_I18N_CONTENTS SET STATUS = 'HIDDEN' WHERE status = 'H';

ALTER TABLE CMS_NEWS_IMAGES ALTER COLUMN status TYPE VARCHAR(9) USING status::VARCHAR(9);
UPDATE CMS_NEWS_IMAGES SET STATUS = 'NEW' WHERE status = 'N';
UPDATE CMS_NEWS_IMAGES SET STATUS = 'DELETED' WHERE status = 'D';
UPDATE CMS_NEWS_IMAGES SET STATUS = 'PUBLISHED' WHERE status = 'P';

ALTER TABLE CMS_TEXT_I18N_CATEGORIES ALTER COLUMN status TYPE VARCHAR(7) USING status::VARCHAR(7);
UPDATE CMS_TEXT_I18N_CATEGORIES SET STATUS = 'NEW' WHERE status = 'N';
UPDATE CMS_TEXT_I18N_CATEGORIES SET STATUS = 'DELETED' WHERE status = 'D';

ALTER TABLE NEWSLETTER_MAIL_GROUPS ALTER COLUMN status TYPE VARCHAR(7) USING status::VARCHAR(7);
UPDATE NEWSLETTER_MAIL_GROUPS SET STATUS = 'NEW' WHERE status = 'N';
UPDATE NEWSLETTER_MAIL_GROUPS SET STATUS = 'DELETED' WHERE status = 'D';

ALTER TABLE NEWSLETTER_MAIL_ADDRESSES ALTER COLUMN status TYPE VARCHAR(8) USING status::VARCHAR(8);
UPDATE NEWSLETTER_MAIL_ADDRESSES SET STATUS = 'NEW' WHERE status = 'N';
UPDATE NEWSLETTER_MAIL_ADDRESSES SET STATUS = 'INACTIVE' WHERE status = 'I';
UPDATE NEWSLETTER_MAIL_ADDRESSES SET STATUS = 'ACTIVE' WHERE status = 'A';
UPDATE NEWSLETTER_MAIL_ADDRESSES SET STATUS = 'DELETED' WHERE status = 'D';
UPDATE NEWSLETTER_MAIL_ADDRESSES SET STATUS = 'ERROR' WHERE status = 'E';

ALTER TABLE NEWSLETTER_TEMPLATES ALTER COLUMN status TYPE VARCHAR(7) USING status::VARCHAR(7);
UPDATE NEWSLETTER_TEMPLATES SET STATUS = 'NEW' WHERE status = 'N';
UPDATE NEWSLETTER_TEMPLATES SET STATUS = 'DELETED' WHERE status = 'D';

ALTER TABLE NEWSLETTER_MAIL ALTER COLUMN status TYPE VARCHAR(9) USING status::VARCHAR(9);
UPDATE NEWSLETTER_MAIL SET STATUS = 'NEW' WHERE status = 'N';
UPDATE NEWSLETTER_MAIL SET STATUS = 'PREPARING' WHERE status = 'P';
UPDATE NEWSLETTER_MAIL SET STATUS = 'SEND' WHERE status = 'S';
UPDATE NEWSLETTER_MAIL SET STATUS = 'DELETED' WHERE status = 'D';

ALTER TABLE NEWSLETTER_DISPATCHED_MAILS ALTER COLUMN status TYPE VARCHAR(5) USING status::VARCHAR(5);
UPDATE NEWSLETTER_DISPATCHED_MAILS SET STATUS = 'SEND' WHERE status = 'S';
UPDATE NEWSLETTER_DISPATCHED_MAILS SET STATUS = 'ERROR' WHERE status = 'E';
